# Generated by Django 4.1 on 2022-08-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_admissionprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
