# Generated by Django 4.1 on 2022-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_admissionprocess_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='demo@gmail.com', max_length=254),
        ),
    ]
